- hosts: ambari-server
  become: true
  tasks:
    - name: Generate blueprint
      template:
        src: "../../files/templates/blueprints/{{blueprint_template_name|default('simple-blueprint.json.j2')}}"
        dest: "/tmp/myblueprint.json"
        owner: "{{ remote_ambari_server_user }}"
        group: "{{ remote_ambari_server_group }}"
        mode: 0777
    - include_role:
        name: ambari-server
        tasks_from: post-blueprint
    - name: Generate cluster creation template
      template:
        src: "../../files/templates/blueprints/{{cluster_template_name|default('simple-cluster.json.j2')}}"
        dest: "/tmp/mycluster.json"
        owner: "{{ remote_ambari_server_user }}"
        group: "{{ remote_ambari_server_group }}"
        mode: 0777
     - include_role:
        name: ambari-server
        tasks_from: post-cluster