- name: Check that pip is installed or not
  command: "pip --version"
  ignore_errors: yes
  register: pip_is_installed
  changed_when: false
- block:
  - name: download get-pip.py
    get_url: url=https://bootstrap.pypa.io/get-pip.py  dest=/tmp
  - name: install pip
    command: "python /tmp/get-pip.py"
  - name: delete get-pip.py
    file: state=absent path=/tmp/get-pip.py
  when: pip_is_installed.rc != 0